// Generated by scripts/optimize-images.mjs (prebuild). Do not edit.
// Real pixel dimensions of every source capture under public/work/<slug>/.
export const captures = {
  "lang-lang": {
    "announcements-full": { width: 2880, height: 4112 },
    "before": { width: 2880, height: 1800 },
    "event-rsvp-full": { width: 2880, height: 5400 },
    "fixtures-full": { width: 2880, height: 4640 },
    "home": { width: 2880, height: 1800 },
    "mobile-announcements-full": { width: 780, height: 5070 },
    "mobile-events": { width: 780, height: 1688 },
    "mobile-home": { width: 780, height: 1688 },
    "mobile-player": { width: 780, height: 1688 },
    "player-full": { width: 2880, height: 3934 },
    "story-full": { width: 2880, height: 5400 },
    "team-full": { width: 2880, height: 5400 },
  },
} as const;

export type CaptureSlug = keyof typeof captures;
export type CaptureFile<S extends CaptureSlug> = keyof (typeof captures)[S];
