// Generates WebP variants (and a downsized JPG fallback) for every source
// screenshot under public/work/** (viewport captures and the *-full.jpg
// full-page captures from scripts/capture.mjs), and writes each source's real
// width/height to src/content/work/captures.generated.ts so `Walk` can derive
// `--walk` from measured dimensions (DESIGN.md 3.4).
// Idempotent: skips outputs newer than source; the TS file is rewritten only
// when its content changes.
import { readdir, stat, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve("public/work");
const GENERATED = path.resolve("src/content/work/captures.generated.ts");
const DESKTOP_WIDTHS = [720, 1080, 1440, 2880];
const MOBILE_WIDTHS = [390, 780];
const DESKTOP_FALLBACK = 1440;
const PHONE_MAX_WIDTH = 1000; // sources at or under this width are phone captures
const WEBP_QUALITY = 78;
const JPEG_QUALITY = 78;

async function newer(out, src) {
  try {
    const [o, s] = await Promise.all([stat(out), stat(src)]);
    return o.mtimeMs >= s.mtimeMs;
  } catch {
    return false;
  }
}

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(p);
    else if (/\.jpe?g$/i.test(entry.name) && !/-\d+\.jpe?g$/i.test(entry.name)) yield p;
  }
}

let made = 0;
/** @type {Record<string, Record<string, { width: number; height: number }>>} */
const dims = {};
await mkdir(ROOT, { recursive: true });
for await (const src of walk(ROOT)) {
  const { dir, name } = path.parse(src);
  const meta = await sharp(src).metadata();
  const width = meta.width ?? 0;
  const height = meta.height ?? 0;
  const phone = width <= PHONE_MAX_WIDTH;
  const widths = phone ? MOBILE_WIDTHS : DESKTOP_WIDTHS;

  const slug = path.relative(ROOT, dir).split(path.sep).join("/");
  (dims[slug] ??= {})[name] = { width, height };

  for (const w of widths) {
    const out = path.join(dir, `${name}-${w}.webp`);
    if (await newer(out, src)) continue;
    await sharp(src).resize({ width: w, withoutEnlargement: true }).webp({ quality: WEBP_QUALITY, effort: 5 }).toFile(out);
    made++;
  }
  const fw = phone ? MOBILE_WIDTHS.at(-1) : DESKTOP_FALLBACK;
  const fallback = path.join(dir, `${name}-${fw}.jpg`);
  if (!(await newer(fallback, src))) {
    await sharp(src).resize({ width: fw, withoutEnlargement: true }).jpeg({ quality: JPEG_QUALITY, mozjpeg: true }).toFile(fallback);
    made++;
  }
}

// Deterministic output: sorted slugs and files.
const lines = [
  "// Generated by scripts/optimize-images.mjs (prebuild). Do not edit.",
  "// Real pixel dimensions of every source capture under public/work/<slug>/.",
  "export const captures = {",
];
for (const slug of Object.keys(dims).sort()) {
  lines.push(`  ${JSON.stringify(slug)}: {`);
  for (const file of Object.keys(dims[slug]).sort()) {
    const { width, height } = dims[slug][file];
    lines.push(`    ${JSON.stringify(file)}: { width: ${width}, height: ${height} },`);
  }
  lines.push("  },");
}
lines.push("} as const;", "", "export type CaptureSlug = keyof typeof captures;", "export type CaptureFile<S extends CaptureSlug> = keyof (typeof captures)[S];", "");
const ts = lines.join("\n");
const prev = await readFile(GENERATED, "utf8").catch(() => "");
if (prev !== ts) {
  await writeFile(GENERATED, ts);
  console.log(`optimize-images: wrote ${path.relative(process.cwd(), GENERATED)}`);
}
console.log(`optimize-images: ${made} file(s) written`);
