// Wordmark generator (DESIGN.md v4 §2.2): "websport" + ".com.au" in Sora 800 as outlined SVG paths, so the
// loader, header and footer never wait for a font. Writes src/components/wordmark.generated.ts (commit it).
//
//   node scripts/wordmark.mjs
//
// Units: 1em = 100. Baseline at y = 0 (y grows down, as in SVG). "websport" tracked -0.045em; ".com.au" drawn at
// 0.62x, tracked -0.03em, baseline-aligned, 0.02em after the word. Re-run only if the spelling changes.
// The layout()/pathData() helpers are copied from scripts/og.mjs (importing og.mjs would run its font fetch).
import { mkdir, readFile, writeFile, access } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import opentype from "opentype.js";

const EM = 100;
const CACHE = path.join(os.tmpdir(), "websport-og-fonts");
const TTF = path.join(CACHE, "sora-800.ttf");
const CSS_URL = "https://fonts.googleapis.com/css2?family=Sora:wght@800";

async function exists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

async function loadFont() {
  await mkdir(CACHE, { recursive: true });
  if (!(await exists(TTF))) {
    // Legacy UA so the css2 API serves TTF (opentype.js cannot read woff2).
    const css = await (await fetch(CSS_URL, { headers: { "User-Agent": "Mozilla/4.0" } })).text();
    const src = /src:\s*url\(([^)]+\.ttf)\)/.exec(css)?.[1];
    if (!src) throw new Error("No Sora 800 TTF in the Google Fonts response");
    await writeFile(TTF, Buffer.from(await (await fetch(src)).arrayBuffer()));
  }
  const b = await readFile(TTF);
  return opentype.parse(b.buffer.slice(b.byteOffset, b.byteOffset + b.byteLength));
}

const n = (v) => (Math.round(v * 100) / 100).toString();

function pathData(p) {
  return p.commands
    .map((c) => {
      switch (c.type) {
        case "M": return `M${n(c.x)} ${n(c.y)}`;
        case "L": return `L${n(c.x)} ${n(c.y)}`;
        case "Q": return `Q${n(c.x1)} ${n(c.y1)} ${n(c.x)} ${n(c.y)}`;
        case "C": return `C${n(c.x1)} ${n(c.y1)} ${n(c.x2)} ${n(c.y2)} ${n(c.x)} ${n(c.y)}`;
        default: return "Z";
      }
    })
    .join("");
}

/** Per-glyph layout with kerning and tracking (em), baseline y = 0, starting at x. */
function layout(font, text, x, size, tracking = 0) {
  const scale = size / font.unitsPerEm;
  const glyphs = [...text].map((ch) => font.charToGlyph(ch));
  let cx = x;
  const out = [];
  let x0 = Infinity, x1 = -Infinity, y0 = Infinity, y1 = -Infinity;
  for (let i = 0; i < glyphs.length; i++) {
    const g = glyphs[i];
    const p = g.getPath(cx, 0, size);
    const bb = p.getBoundingBox();
    x0 = Math.min(x0, bb.x1); x1 = Math.max(x1, bb.x2); y0 = Math.min(y0, bb.y1); y1 = Math.max(y1, bb.y2);
    const kern = i + 1 < glyphs.length ? font.getKerningValue(g, glyphs[i + 1]) || 0 : 0;
    const adv = ((g.advanceWidth || 0) + kern) * scale + tracking * size;
    out.push({ ch: text[i], d: pathData(p), x: +n(cx), advance: +n(adv) });
    cx += adv;
  }
  return { glyphs: out, end: cx, bbox: { x0, x1, y0, y1 } };
}

const font = await loadFont();
const word = layout(font, "websport", 0, EM, -0.045);
// ".com.au" starts 0.02em after the word's ink edge.
const tldStart = word.bbox.x1 + 0.02 * EM;
const tld = layout(font, ".com.au", tldStart, EM * 0.62, -0.03);

// Shared vertical box (so word and tld can share one height and keep their baselines together).
const top = Math.floor(Math.min(word.bbox.y0, tld.bbox.y0));
const bottom = Math.ceil(Math.max(word.bbox.y1, tld.bbox.y1));
const cap = -(font.tables.os2.sCapHeight ?? 700) * (EM / font.unitsPerEm);
const xh = -(font.tables.os2.sxHeight ?? 500) * (EM / font.unitsPerEm);

const data = {
  em: EM,
  top,
  height: bottom - top,
  capHeight: +n(-cap),
  xHeight: +n(-xh),
  word: { x0: +n(word.bbox.x0), x1: +n(word.bbox.x1), glyphs: word.glyphs },
  tld: { x0: +n(tld.bbox.x0), x1: +n(tld.bbox.x1), glyphs: tld.glyphs },
};

const file = `// Generated by scripts/wordmark.mjs (Sora 800 outlines). Do not edit by hand.
// Units: 1em = ${EM}; baseline y = 0; \`top\`/\`height\` is the shared vertical box of both parts.
export type WmGlyph = { ch: string; d: string; x: number; advance: number };
export type WmPart = { x0: number; x1: number; glyphs: WmGlyph[] };
export const WM: { em: number; top: number; height: number; capHeight: number; xHeight: number; word: WmPart; tld: WmPart } = ${JSON.stringify(data, null, 1)};
`;
const dest = path.resolve("src/components/wordmark.generated.ts");
await writeFile(dest, file);
console.log(`[wordmark] wrote ${path.relative(process.cwd(), dest)} (${(file.length / 1024).toFixed(1)} KB), box top ${top} h ${bottom - top}, word ${n(word.bbox.x0)}..${n(word.bbox.x1)}, tld ${n(tld.bbox.x0)}..${n(tld.bbox.x1)}`);
